#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/debian_hardening
- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
  listen: Restart sshd

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted