#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/common
timezone: Europe/Zurich
common_base_packages:
  - nano
  - curl
  - htop
  - git
  - sudo
  - locales
  - ca-certificates

common_admin_user: admin
common_admin_shell: /bin/bash
common_admin_home: "/home/{{ common_admin_user }}"
common_admin_groups:
  - sudo
common_admin_authorized_keys: []
common_install_tailscale: false
common_system_locale: de_CH.UTF-8
common_system_language: en_US.UTF-8