#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/common
timezone: Europe/Zurich
common_base_packages:
  - nano
  - curl
  - htop
  - git
  - sudo

common_admin_user: admin
common_admin_shell: /bin/bash
common_admin_home: "/home/{{ common_admin_user }}"
common_admin_groups:
  - sudo
common_admin_authorized_keys: []
