#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/komodo

# The follwing variables have no default and should be set:
# komodo_deployment_directory
# komodo_postgres_version
# komodo_ferretdb_version
# komodo_core_version
# komodo_periphery_version
# komodo_host_url

# Optional variables with default values:
komodo_timezone: "Europe/Zurich"

# Secret variables that should be set securely:
# komodo_secret_db_username
# komodo_secret_db_password
# komodo_secret_passkey
# komodo_secret_webhook_secret
# komodo_secret_jwt_secret


