#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/debian_hardening
# SSH policy
ssh_password_auth: false
ssh_kbdinteractive_auth: false
ssh_pubkey_auth: true
ssh_permit_root_login: "no"      # "no" | "prohibit-password" | "yes"
ssh_max_auth_tries: 3
ssh_login_grace_time: "30s"
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_allow_groups: ["sudo"]

# Weekly upgrades instead of daily
hardening_enable_weekly_upgrade: true

# Optional service disables
hardening_disable_services: []

debian_hardening_logs_max_size: "100M"
debian_hardening_logs_retention: "1month"
debian_hardening_enable_persistent_logs: true