#SPDX-License-Identifier: MIT-0
---

# NAS / SMB settings
# not optional variables
# backup_smb_share:
# backup_smb_username:
# backup_smb_password:

backup_smb_mountpoint: "/mnt/backup"
backup_smb_creds_file: "/root/.smb/credentials"
backup_smb_uid: 1000
backup_smb_gid: 1000

# snapshot script configuration
backup_snapshot_script_path: /usr/local/sbin/backup-snapshot.sh
backup_snapshot_source: /
backup_snapshot_local_path: /.snapshots
backup_snapshot_remote_path: "{{ backup_smb_mountpoint }}/{{ hostname | default(inventory_hostname) }}/snapshots"
backup_snapshot_retention: 3

# cron configuration
backup_snapshot_cron_minute: "0"
backup_snapshot_cron_hour: "2"
backup_snapshot_cron_user: root
