$ANSIBLE_VAULT;1.1;AES256
61383034303063306438643632333265313431663838393732366433636234306530356434313732
6331643462383562306532636537373737373736386366310a386232366533303034343966333239
39646562373663323463626264316639326164646536366463306434356135393762316563643739
3034333264623961320a353237613835356533366665663439656266626238396230623864393739
66396531653933666331653234626561653439613862306136333962636662393361356134323233
62326133363038366638396130366566393731366138303264383332356465666130333633333936
64353933353634633666656134323463356136646666343466636566636661393163303235303134
38613034353966346664393636656464363739393931313134623264653534636362656436326365
30363732653663313335326136663330646361373262316565363035353261393236383965616432
39663363393361626466646530636134323633326630353834353665626539346331633062653234
34393063653466663861326162623063626130646531646162366232306430643635343632356237
35656465393662366231383734326266343437663762373963306230323731663738653036616630
63313061613862383830653239613135616536363636313766313936383464616466653831343738
32326462363736333465333737316361336366356631633232313235356135306235333137346436
35633330376635356137363664356532366166313933333662353434383734306430373434653665
63386234396335373361653333383735633434396138353339643435326465643461383161623633
33393763383433316262636265653730396435616462346565323738626637303263393536663633
38353332366130303261343739313162326438643363653134633738333139626536323335623763
64373531363730333963636631646561313930366639356339353861343434393435666338373137
65373433393165356336663436373436313665356234313133326562333530373463353435326339
3933
